### ISSUE TITLE
Sanam Tamang: The buttons are not linked in account session login and create an account

### ISSUE THREAD

**Issue by Nimesh-shta** [sanamxgit/pet-adoption-system-html-css-js-php#1]
![image](https://github.com/sanamxgit/pet-adoption-system-html-css-js-php/assets/127822872/7d0c3f7b-e510-4d1c-87ed-293c237c9102)

**Comment by sanamxgit** [comment]
![image](https://github.com/sanamxgit/pet-adoption-system-html-css-js-php/assets/124186419/96e3941b-7bca-4891-a35c-39aad37d2eb7)
****
