### ISSUE TITLE
Multiple Choices on Payment Method

### ISSUE THREAD

**Issue by LMvibek10** [sanamxgit/pet-adoption-system-html-css-js-php#2]
![issue_sanam](https://github.com/sanamxgit/pet-adoption-system-html-css-js-php/assets/119830540/28a1e896-b0b9-4a62-834c-99f3370ec25d)

**Comment by sanamxgit** [comment]
![image](https://github.com/sanamxgit/pet-adoption-system-html-css-js-php/assets/124186419/49171e9e-2da5-441d-9a83-729042aced43)
